[package]
name = "sender"
version = "0.1.0"
edition = "2021"

[lib]
path = "sender.rs"

[dependencies]
tokio.workspace = true
xdpilone.workspace = true
anyhow.workspace = true
etherparse.workspace = true
log.workspace = true
aya.workspace = true